# Custom Language File for Launcher Customizer

[ejs.app]
title = "Fateless SMP"

[ejs.landing]
mediaGitHubURL = "#"
mediaXURL = "https://x.com/FatelessSMP"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/WtEANQvgGW"

[ejs.settings]
sourceGithubLink = ""
supportLink = ""

[ejs.welcome]
welcomeHeader = "Bienvenue sur Fateless SMP"
welcomeDescription = "#"
welcomeDescCTA = "#"
